QTrack/QTrack/Controllers/QRController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntitiyFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QTrack.Controllers
{
    public class QRController : Controller
    {
        QRManager qm = new QRManager(new EfQRDal());
        CompanyManager cm = new CompanyManager(new EfCompanyDal());
        ProductManager pm = new ProductManager(new EfProductDal());

        //[Authorize(Roles="Admin")]
        public ActionResult Index()
        {
            var QRvalue = qm.GetList();
            return View(QRvalue);
        }
        public ActionResult AddQR(QR p)
        {
            QRValidator QRvalid = new QRValidator();
            ValidationResult results = QRvalid.Validate(p);

            if (results.IsValid)
            {
                qm.QRAdd(p);
                TempData["QRtoastr"] = "Added";
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    TempData["QRtoastr"] = "Error";
                }
            }
           
            return RedirectToAction("Index");
        }
        public PartialViewResult QRPartial()            
        {
            List<SelectListItem> valuecompany = (from x in cm.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.CNAME,
                                                     Value = x.COMPANYID.ToString()

                                                 }).ToList();

            List<SelectListItem> valueproduct = (from x in pm.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.PNAME,
                                                     Value = x.PRODUCTID.ToString()

                                                 }).ToList();

            ViewBag.cv = valuecompany;
            ViewBag.pv = valueproduct;

            return PartialView();
        }

        [HttpGet]
        public ActionResult EditQR(int id)
        {
            List<SelectListItem> valuecompany = (from x in cm.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.CNAME,
                                                     Value = x.COMPANYID.ToString()

                                                 }).ToList();

            List<SelectListItem> valueproduct = (from x in pm.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.PNAME,
                                                     Value = x.PRODUCTID.ToString()

                                                 }).ToList();

            ViewBag.cv = valuecompany;
            ViewBag.pv = valueproduct;

            var QRvalue = qm.GetById(id);
            return View(QRvalue);
        }
        [HttpPost]
        public ActionResult EditQR(QR p)
        {
            QRValidator QRvalid = new QRValidator();
            ValidationResult results = QRvalid.Validate(p);

            if (results.IsValid)
            {
                qm.QRUpdate(p);
                TempData["QRtoastr"] = "Added";
                return RedirectToAction("Index", "QR");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    TempData["QRtoastr"] = "Error";
                }
            }
            
            return RedirectToAction("Index","QR");
        }

        public PartialViewResult QRCreate( )
        {

            return PartialView();
        }

    }
}

QTrack/QTrack/Controllers/QRHistoryController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntitiyFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QTrack.Controllers
{
    public class QRHistoryController : Controller
    {

        QRHistoryManager qm = new QRHistoryManager(new EfQRHistoryDal());
        QRManager QRm = new QRManager(new EfQRDal());

        
        public ActionResult Index(int id)
        {
            var QRHValue = qm.GetListById(id);

            return View(QRHValue);
        }
        [AllowAnonymous]
        public ActionResult UserIndex(int id)
        {
            var QRHvalue = qm.GetListById(id);
            var QRV = QRm.GetById(id);
            ViewBag.QR = QRV.QRCODE;
            return View(QRHvalue);
        }

        [HttpPost]
        public ActionResult AddQRHistory(QRHistory p)
        {
            qm.QRHistoryAdd(p);

            return RedirectToAction("Index", "QR");
        }

        public PartialViewResult QRHistoryPartial()
        {
            List<SelectListItem> historyvalue = (from x in QRm.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.QRCODE.ToString(),
                                                     Value = x.QRID.ToString()

                                                 }).ToList();



            ViewBag.hiva = historyvalue;
            return PartialView();
        }
    }
}

QTrack/QTrack/Views/QR/EditQR.cshtml
@model EntityLayer.Concrete.QR
@{
    ViewBag.Title = "EditQR";
    Layout = "~/Views/_Layout.cshtml";
}

<div style="margin-top:85px">
    <div class="col-md-12">
        <div class="tab-pane active" id="tab_0">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-edit"></i>QR Code's / Edit Page
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse"> </a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <!-- BEGIN FORM-->
                    <form action="/QR/EditQR" method="post" class="form-horizontal">
                        <div class="form-body">
                            <div class="form-group last">
                                <label class="col-md-3 control-label">QR Code</label>
                                <div class="col-md-4">
                                    <span class="form-control-static"> # @Html.DisplayFor(x => x.QRCODE) </span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Location</label>
                                <div class="col-md-4">
                                    <input type="text" class="form-control spinner input-circle" name="LOCATION" value="@Html.DisplayFor(x => x.Product.LOCATION)">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Product Name</label>
                                <div class="col-md-4">
                                    <select name="PRODUCTID" class="form-control spinner input-circle">
                                        <option disabled>@Html.DisplayFor(x => x.Product.PNAME)</option>
                                        @foreach (var x in ViewBag.pv)
                                        {
                                            <option name="PRODUCTID" value="@x.Value">@x.Text</option>
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Company Name</label>
                                <div class="col-md-4">
                                    <select name="COMPANYID" class="form-control spinner input-circle">
                                        <option disabled>@Html.DisplayFor(x => x.Company.CNAME)</option>
                                        @foreach (var x in ViewBag.cv)
                                        {
                                            <option name="COMPANYID" value="@x.Value">@x.Text</option>
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Other</label>
                                <div class="col-md-4">
                                    <textarea class="form-control spinner input-circle" name="OTHER" value="@Html.DisplayFor(x => x.OTHER)">@Html.DisplayFor(x => x.OTHER)</textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Exp Date</label>
                                <div class="col-md-4">
                                    <input class="form-control form-control-inline input-medium date-picker" size="12" type="text" value="@Html.DisplayFor(x => x.EXPDATE)" name="EXPDATE" data-date-format="dd-mm-yyyy" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Factory Date</label>
                                <div class="col-md-4">
                                    <input class="form-control form-control-inline input-medium date-picker" size="12" type="text" value="@Html.DisplayFor(x => x.FACTORYDATE)" name="FACTORYDATE" data-date-format="dd-mm-yyyy" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Fill Date</label>
                                <div class="col-md-4">
                                    <input class="form-control form-control-inline input-medium date-picker" size="12" type="text" value="@Html.DisplayFor(x => x.FILLDATE)" name="FILLDATE" data-date-format="dd-mm-yyyy" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">ReFill Date</label>
                                <div class="col-md-8">
                                    <input class="form-control form-control-inline input-medium date-picker" size="12" type="text" value="@Html.DisplayFor(x => x.REFILLDATE)" name="REFILLDATE" data-date-format="dd-mm-yyyy" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Status</label>
                                <div class="col-md-4">
                                    <input type="checkbox" name="QRSTATUS" class="make-switch" checked value="True" data-on-text="Active" data-off-text="Passive" data-on-color="success" data-off-color="danger">
                                    <input type="hidden" name="QRCODE" value="@Html.DisplayFor(x=>x.QRCODE)" />
                                    <input type="hidden" name="QRID" value="@Html.DisplayFor(x=>x.QRID)" />
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <button type="submit" class="btn btn-circle green">Save Changes</button>
                                    <a href="~/QR/Index" class="btn btn-circle grey-salsa btn-outline">Back</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

QTrack/QTrack/Views/QR/Index.cshtml
@using EntityLayer.Concrete
@model List<QR>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Layout.cshtml";
}

<div style="margin-top:100px">
    <div class="row" >
        <div class="col-md-10">
            <button class="btn btn-md purple" style="margin-left:4px" data-toggle="modal" data-target="#static">
                New QR Code Item
                <i class="fa fa-plus"></i>
            </button>
            <button class="btn btn-md yellow" data-toggle="modal" data-target="#static2">
                New QR Issue
                <i class="fa fa-plus"></i>
            </button>
            <button class="btn btn-md blue" data-toggle="modal" data-target="#static3">
                QR Create
                <i class="fa fa-plus"></i>
            </button>
        </div>
    </div>
    
    <br />
    
   
    <div class="col-md-12">
        <div class="portlet-body form">
            <div class="portlet light bordered">

                <div class="portlet-title">
                    <div class="caption font-dark">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">QR Code's List</span>
                    </div>
                </div>
                <div class="portlet-body">
                    @*<div class="table-scrollable">*@
                    @*<table class="table table-striped table-bordered table-advance table-hover">*@
                    <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_3" cellspacing="0">
                        <thead>
                            <tr>
                                <th>
                                    <i class="fa fa-briefcase"></i> QR Code
                                </th>
                                <th>History</th>
                                <th>
                                    <i class="fa fa-arrow-circle-down "></i> Status / Edit
                                </th>
                                <th class="none">
                                    <i class="fa fa-briefcase"></i> Product
                                </th>
                                <th>
                                    <i class="fa fa-clipboard"></i> Location
                                </th>
                                <th>
                                    <i class="fa fa-user"></i> Company
                                </th>

                                <th>
                                    <i class="fa fa-phone"></i> Contact
                                </th>
                                <th>
                                    <i class="fa fa-mail-reply"></i> Expiration Date
                                </th>
                                <th class="none">
                                    <i class="fa fa-briefcase"></i> Serial
                                </th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@item.QRCODE</td>

                                <td align="center">
                                    <a href="~/QRHistory/Index?id=@item.QRID" class="btn btn-icon-only yellow">
                                        <i class="fa fa-book"></i>
                                    </a>
                                </td>

                                @switch (item.QRSTATUS)
                                {
                                    case true:
                                        <td width="2" align="center" class="font-green-haze"><a href="~/QR/EditQR?id=@item.QRID" class="label label-md label-success">Aktif</a></td>
                                        break;
                                    case false:
                                        <td width="2" align="center" class="font-green-haze"><a href="~/QR/EditQR?id=@item.QRID" class="label label-sm label-danger">Pasif</a></td>
                                        break;
                                }


                                <td align="center">@item.Product.PNAME</td>
                                <td align="center">
                                    <a href="@item.Product.LOCATION" target="_blank" class="btn btn-icon-only red">
                                        <i class="fa fa-map"></i>
                                    </a>
                                </td>

                                <td>@item.Company.CNAME </td>
                                <td>@item.Company.CPERSON - @item.Company.CPHONE</td>
                                <td> @Convert.ToDateTime(item.EXPDATE).ToString("dd/MM/yyyy")</td>
                                <td>@item.Product.SERIAL </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


@Html.Action("QRPartial", "QR")
@Html.Action("QRHistoryPartial", "QRHistory")
@Html.Action("QRCreate", "QR")

<script src="~/Layout/js/jquery.js"></script>

<script>
	$(document).ready(function()
    {
        switch ('@TempData["QRtoastr"]') {
            case "Added":
                toastr.success('Kayıt Başarılır','Register');
                break;
            case "Error":
                toastr.error('Kayıt Başarısız !!', 'Not Register');
                break;
            case "Edit":
                toastr.warning('Kayıt Başarısız !!', 'Not Register');
                break;
            default:
        }
		});
</script>

QTrack/QTrack/Views/QR/QRCreate.cshtml
<div id="static3" class="modal" tabindex="-1" data-backdrop="static" data-keyboard="true" data-width="500">
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title"> QR Generate</h2>
        </div>
        <div class="modal-body">
            <div style="height:auto" data-always-visible="1" data-rail-visible1="1">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group form-md-line-input">
                            <input type="text" class="form-control" id="qr" value="https://localhost:44396/QRHistory/userIndex?id=">
                            <label for="form_control_1">Generate Link</label>
                            <span class="help-block">Query..</span>
                        </div>
                    </div>                    
                </div>
                <div id="divYazdir">
                    <div id="qrcode"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-outline dark">Cancel</button>
                    <button type="button" data-dismiss="modal" class="btn btn-outline blue" onclick="javascript: printDiv('divYazdir');">Print <i class="fa fa-print"></i></button>                  
                </div>               
            </div>
        </div>
    </div>
</div>

QTrack/QTrack/Views/QR/QRPartial.cshtml
@model EntityLayer.Concrete.QR

<div id="static" class="modal" tabindex="-1" data-backdrop="static" data-keyboard="true" data-width="1000">
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title"> Product Register</h2>
        </div>
        <form method="post" action="/QR/AddQR">
            <div class="modal-body">
                @*<div style="height:400px" data-always-visible="1" data-rail-visible1="1">*@
                <div style="height:auto" data-always-visible="1" data-rail-visible1="1">
                    <div class="row">
                        <div class="col-md-6">
                            <p>
                                <label> QR Code</label>
                                <input type="text" name="QRCODE" class="form-control" />
                            </p>
                            <p>
                                <label> Company</label>
                                <select name="COMPANYID" class="form-control col-md-4">
                                    <option selected disabled>- Select -</option>
                                    @foreach (var x in ViewBag.cv)
                                    {
                                        <option value="@x.Value">@x.Text</option>

                                    }
                                </select>
                            </p>
                            <br />
                            <p>
                                <label> Product</label>
                                <select name="PRODUCTID" class="form-control">
                                    <option selected disabled>- Select -</option>
                                    @foreach (var x in ViewBag.pv)
                                    {
                                        <option value="@x.Value">@x.Text</option>

                                    }
                                </select>
                            </p>
                            <p>
                                <label> Other </label>
                                @*<input type="text" name="OTHER" class="form-control">*@
                                <textarea name="OTHER" class="form-control"> </textarea>
                            </p>
                        </div>
                        <div class="col-md-4">
                            <p>
                                <label> Factory Date </label>
                                <input class="form-control form-control-inline input-medium date-picker" size="16" type="text" value="" name="FACTORYDATE" data-date-format="dd-mm-yyyy" />
                            </p>
                            <p>
                                <label> Fill Date </label>
                                <input class="form-control form-control-inline input-medium date-picker" size="16" type="text" value="" name="FILLDATE" data-date-format="dd-mm-yyyy" />
                            </p>
                            <p>
                                <label> ReFill Date </label>
                                <input class="form-control form-control-inline input-medium date-picker" size="16" type="text" value="" name="REFILLDATE" data-date-format="dd-mm-yyyy" />
                            </p>
                            <p>
                                <label> Exp Date </label>
                                <input class="form-control form-control-inline input-medium date-picker" size="16" type="text" value="" name="EXPDATE" data-date-format="dd-mm-yyyy" />
                            </p>
                            <p>
                                <label> QR Status </label><br />
                                <input type="checkbox" name="QRSTATUS" class="make-switch" checked value="True" data-on-text="Active" data-off-text="Passive">
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                @*<div class="col-md-2">
                    <input type="checkbox" name="QRSTATUS" class="make-switch" checked value="True" data-on-text="Active" data-off-text="Passive">
                </div>*@
                <button type="button" data-dismiss="modal" class="btn btn-outline dark">Cancel</button>
                <button class="btn green">Save Changes</button>
            </div>
        </form>
    </div>
</div>